import type { Metadata } from "next";
import "./globals.css";
import { GlobalExpertProvider } from "@/components/TalkToOurExpert/TalkToExpertButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <GlobalExpertProvider>
          {children}
        </GlobalExpertProvider>
      </body>
    </html>
  );
}
